/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include<stdio.h>
#include<stdlib.h>

int main(){
    int limit = 4000000;
    int a = 1, b = 1, c = a + b;
    int sum = 0;
    while(c < limit){
        sum += c;
        a = b + c; 
        b = c + a;
        c = a + b;
    }
    printf("The answer is: %d", sum);
    return 0;
}